/*
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import com.ufrn.atad.ide.contentassist.antlr.internal.InternalAtadParser;
import com.ufrn.atad.services.AtadGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class AtadParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(AtadGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, AtadGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getComandosAcaoAccess().getAlternatives(), "rule__ComandosAcao__Alternatives");
			builder.put(grammarAccess.getDeclaraComandoAccess().getGroup(), "rule__DeclaraComando__Group__0");
			builder.put(grammarAccess.getClicarAccess().getGroup(), "rule__Clicar__Group__0");
			builder.put(grammarAccess.getVerifiqueAccess().getGroup(), "rule__Verifique__Group__0");
			builder.put(grammarAccess.getAdicaoComandoAccess().getGroup(), "rule__AdicaoComando__Group__0");
			builder.put(grammarAccess.getQuandoAccess().getGroup(), "rule__Quando__Group__0");
			builder.put(grammarAccess.getDeclaraComandoAccess().getComandosAssignment_0(), "rule__DeclaraComando__ComandosAssignment_0");
			builder.put(grammarAccess.getDeclaraComandoAccess().getAcoesAssignment_1(), "rule__DeclaraComando__AcoesAssignment_1");
			builder.put(grammarAccess.getDeclaraComandoAccess().getVerificacaoAssignment_2(), "rule__DeclaraComando__VerificacaoAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private AtadGrammarAccess grammarAccess;

	@Override
	protected InternalAtadParser createParser() {
		InternalAtadParser result = new InternalAtadParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public AtadGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AtadGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
