/*
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AtadStandaloneSetup extends AtadStandaloneSetupGenerated {

	public static void doSetup() {
		new AtadStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
