/*
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AtadRuntimeModule extends AbstractAtadRuntimeModule {
}
