/*
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.ui;

import com.google.inject.Injector;
import com.ufrn.atad.ui.internal.AtadActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AtadExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(AtadActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		AtadActivator activator = AtadActivator.getInstance();
		return activator != null ? activator.getInjector(AtadActivator.COM_UFRN_ATAD_ATAD) : null;
	}

}
