/*
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.ufrn.atad.AtadRuntimeModule;
import com.ufrn.atad.AtadStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AtadIdeSetup extends AtadStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AtadRuntimeModule(), new AtadIdeModule()));
	}
	
}
