/*
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.ui.tests;

import com.google.inject.Injector;
import com.ufrn.atad.ui.internal.AtadActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AtadUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AtadActivator.getInstance().getInjector("com.ufrn.atad.Atad");
	}

}
