/*
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AtadUiModule extends AbstractAtadUiModule {

	public AtadUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
