/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.ufrn.atad.atad.AtadPackage
 * @generated
 */
public interface AtadFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AtadFactory eINSTANCE = com.ufrn.atad.atad.impl.AtadFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Declara Comando</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declara Comando</em>'.
   * @generated
   */
  DeclaraComando createDeclaraComando();

  /**
   * Returns a new object of class '<em>Comando</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comando</em>'.
   * @generated
   */
  Comando createComando();

  /**
   * Returns a new object of class '<em>Clicar</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Clicar</em>'.
   * @generated
   */
  Clicar createClicar();

  /**
   * Returns a new object of class '<em>Navegar</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Navegar</em>'.
   * @generated
   */
  Navegar createNavegar();

  /**
   * Returns a new object of class '<em>Escrever</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Escrever</em>'.
   * @generated
   */
  Escrever createEscrever();

  /**
   * Returns a new object of class '<em>Comandos Acao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comandos Acao</em>'.
   * @generated
   */
  ComandosAcao createComandosAcao();

  /**
   * Returns a new object of class '<em>Verifique</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Verifique</em>'.
   * @generated
   */
  Verifique createVerifique();

  /**
   * Returns a new object of class '<em>Comandos Validadores</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comandos Validadores</em>'.
   * @generated
   */
  ComandosValidadores createComandosValidadores();

  /**
   * Returns a new object of class '<em>Adicao Comando</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Adicao Comando</em>'.
   * @generated
   */
  AdicaoComando createAdicaoComando();

  /**
   * Returns a new object of class '<em>Quando</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Quando</em>'.
   * @generated
   */
  Quando createQuando();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AtadPackage getAtadPackage();

} //AtadFactory
