/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.ufrn.atad.atad.AtadPackage
 * @generated
 */
public interface AtadFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AtadFactory eINSTANCE = com.ufrn.atad.atad.impl.AtadFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Declara Comando</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declara Comando</em>'.
   * @generated
   */
  DeclaraComando createDeclaraComando();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AtadPackage getAtadPackage();

} //AtadFactory
