/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clicar</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufrn.atad.atad.Clicar#getTipoLocalizador <em>Tipo Localizador</em>}</li>
 * </ul>
 *
 * @see com.ufrn.atad.atad.AtadPackage#getClicar()
 * @model
 * @generated
 */
public interface Clicar extends ComandosAcao
{
  /**
   * Returns the value of the '<em><b>Tipo Localizador</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo Localizador</em>' attribute.
   * @see #setTipoLocalizador(String)
   * @see com.ufrn.atad.atad.AtadPackage#getClicar_TipoLocalizador()
   * @model
   * @generated
   */
  String getTipoLocalizador();

  /**
   * Sets the value of the '{@link com.ufrn.atad.atad.Clicar#getTipoLocalizador <em>Tipo Localizador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo Localizador</em>' attribute.
   * @see #getTipoLocalizador()
   * @generated
   */
  void setTipoLocalizador(String value);

} // Clicar
