/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clicar</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.ufrn.atad.atad.AtadPackage#getClicar()
 * @model
 * @generated
 */
public interface Clicar extends ComandosAcao
{
} // Clicar
