/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comandos Acao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufrn.atad.atad.ComandosAcao#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see com.ufrn.atad.atad.AtadPackage#getComandosAcao()
 * @model
 * @generated
 */
public interface ComandosAcao extends AdicaoComando, Quando
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.ufrn.atad.atad.AtadPackage#getComandosAcao_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.ufrn.atad.atad.ComandosAcao#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // ComandosAcao
