/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comandos Validadores</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.ufrn.atad.atad.AtadPackage#getComandosValidadores()
 * @model
 * @generated
 */
public interface ComandosValidadores extends EObject
{
} // ComandosValidadores
