/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comandos Acao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufrn.atad.atad.ComandosAcao#getComando <em>Comando</em>}</li>
 * </ul>
 *
 * @see com.ufrn.atad.atad.AtadPackage#getComandosAcao()
 * @model
 * @generated
 */
public interface ComandosAcao extends Comando, Quando
{
  /**
   * Returns the value of the '<em><b>Comando</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comando</em>' containment reference.
   * @see #setComando(EObject)
   * @see com.ufrn.atad.atad.AtadPackage#getComandosAcao_Comando()
   * @model containment="true"
   * @generated
   */
  EObject getComando();

  /**
   * Sets the value of the '{@link com.ufrn.atad.atad.ComandosAcao#getComando <em>Comando</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comando</em>' containment reference.
   * @see #getComando()
   * @generated
   */
  void setComando(EObject value);

} // ComandosAcao
