/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declara Comando</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufrn.atad.atad.DeclaraComando#getComandos <em>Comandos</em>}</li>
 * </ul>
 *
 * @see com.ufrn.atad.atad.AtadPackage#getDeclaraComando()
 * @model
 * @generated
 */
public interface DeclaraComando extends EObject
{
  /**
   * Returns the value of the '<em><b>Comandos</b></em>' containment reference list.
   * The list contents are of type {@link com.ufrn.atad.atad.Comando}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comandos</em>' containment reference list.
   * @see com.ufrn.atad.atad.AtadPackage#getDeclaraComando_Comandos()
   * @model containment="true"
   * @generated
   */
  EList<Comando> getComandos();

} // DeclaraComando
