/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Espera</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ufrn.atad.atad.Espera#getTipoLocalizador <em>Tipo Localizador</em>}</li>
 *   <li>{@link com.ufrn.atad.atad.Espera#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see com.ufrn.atad.atad.AtadPackage#getEspera()
 * @model
 * @generated
 */
public interface Espera extends Comando
{
  /**
   * Returns the value of the '<em><b>Tipo Localizador</b></em>' attribute.
   * The literals are from the enumeration {@link com.ufrn.atad.atad.TipoLocalizadores}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo Localizador</em>' attribute.
   * @see com.ufrn.atad.atad.TipoLocalizadores
   * @see #setTipoLocalizador(TipoLocalizadores)
   * @see com.ufrn.atad.atad.AtadPackage#getEspera_TipoLocalizador()
   * @model
   * @generated
   */
  TipoLocalizadores getTipoLocalizador();

  /**
   * Sets the value of the '{@link com.ufrn.atad.atad.Espera#getTipoLocalizador <em>Tipo Localizador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo Localizador</em>' attribute.
   * @see com.ufrn.atad.atad.TipoLocalizadores
   * @see #getTipoLocalizador()
   * @generated
   */
  void setTipoLocalizador(TipoLocalizadores value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.ufrn.atad.atad.AtadPackage#getEspera_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.ufrn.atad.atad.Espera#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Espera
