/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Espera Clicavel</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.ufrn.atad.atad.AtadPackage#getEsperaClicavel()
 * @model
 * @generated
 */
public interface EsperaClicavel extends Espera
{
} // EsperaClicavel
