/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Tipo Localizadores</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see com.ufrn.atad.atad.AtadPackage#getTipoLocalizadores()
 * @model
 * @generated
 */
public enum TipoLocalizadores implements Enumerator
{
  /**
   * The '<em><b>XPATH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #XPATH_VALUE
   * @generated
   * @ordered
   */
  XPATH(0, "XPATH", "xpath"),

  /**
   * The '<em><b>ID</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ID_VALUE
   * @generated
   * @ordered
   */
  ID(1, "ID", "id"),

  /**
   * The '<em><b>CSSSELECTOR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CSSSELECTOR_VALUE
   * @generated
   * @ordered
   */
  CSSSELECTOR(2, "CSSSELECTOR", "cssSelector"),

  /**
   * The '<em><b>CLASSNAME</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CLASSNAME_VALUE
   * @generated
   * @ordered
   */
  CLASSNAME(3, "CLASSNAME", "className"),

  /**
   * The '<em><b>LINKTEXT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LINKTEXT_VALUE
   * @generated
   * @ordered
   */
  LINKTEXT(4, "LINKTEXT", "linkText");

  /**
   * The '<em><b>XPATH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #XPATH
   * @model literal="xpath"
   * @generated
   * @ordered
   */
  public static final int XPATH_VALUE = 0;

  /**
   * The '<em><b>ID</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ID
   * @model literal="id"
   * @generated
   * @ordered
   */
  public static final int ID_VALUE = 1;

  /**
   * The '<em><b>CSSSELECTOR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CSSSELECTOR
   * @model literal="cssSelector"
   * @generated
   * @ordered
   */
  public static final int CSSSELECTOR_VALUE = 2;

  /**
   * The '<em><b>CLASSNAME</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CLASSNAME
   * @model literal="className"
   * @generated
   * @ordered
   */
  public static final int CLASSNAME_VALUE = 3;

  /**
   * The '<em><b>LINKTEXT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LINKTEXT
   * @model literal="linkText"
   * @generated
   * @ordered
   */
  public static final int LINKTEXT_VALUE = 4;

  /**
   * An array of all the '<em><b>Tipo Localizadores</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final TipoLocalizadores[] VALUES_ARRAY =
    new TipoLocalizadores[]
    {
      XPATH,
      ID,
      CSSSELECTOR,
      CLASSNAME,
      LINKTEXT,
    };

  /**
   * A public read-only list of all the '<em><b>Tipo Localizadores</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<TipoLocalizadores> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Tipo Localizadores</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TipoLocalizadores get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TipoLocalizadores result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Tipo Localizadores</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TipoLocalizadores getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TipoLocalizadores result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Tipo Localizadores</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TipoLocalizadores get(int value)
  {
    switch (value)
    {
      case XPATH_VALUE: return XPATH;
      case ID_VALUE: return ID;
      case CSSSELECTOR_VALUE: return CSSSELECTOR;
      case CLASSNAME_VALUE: return CLASSNAME;
      case LINKTEXT_VALUE: return LINKTEXT;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private TipoLocalizadores(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //TipoLocalizadores
