/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verifique Presente</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.ufrn.atad.atad.AtadPackage#getVerifiquePresente()
 * @model
 * @generated
 */
public interface VerifiquePresente extends ComandosValidadores
{
} // VerifiquePresente
