/*
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAtadScopeProvider extends DelegatingScopeProvider {
}
