/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad.impl;

import com.ufrn.atad.atad.AtadPackage;
import com.ufrn.atad.atad.Clicar;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Clicar</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ClicarImpl extends ComandosAcaoImpl implements Clicar
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ClicarImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AtadPackage.Literals.CLICAR;
  }

} //ClicarImpl
