/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad.impl;

import com.ufrn.atad.atad.AtadPackage;
import com.ufrn.atad.atad.ComandosValidadores;
import com.ufrn.atad.atad.VerifiquePresente;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Comandos Validadores</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.ufrn.atad.atad.impl.ComandosValidadoresImpl#getVerifique <em>Verifique</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComandosValidadoresImpl extends ComandoImpl implements ComandosValidadores
{
  /**
   * The cached value of the '{@link #getVerifique() <em>Verifique</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVerifique()
   * @generated
   * @ordered
   */
  protected VerifiquePresente verifique;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComandosValidadoresImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AtadPackage.Literals.COMANDOS_VALIDADORES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VerifiquePresente getVerifique()
  {
    return verifique;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVerifique(VerifiquePresente newVerifique, NotificationChain msgs)
  {
    VerifiquePresente oldVerifique = verifique;
    verifique = newVerifique;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AtadPackage.COMANDOS_VALIDADORES__VERIFIQUE, oldVerifique, newVerifique);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVerifique(VerifiquePresente newVerifique)
  {
    if (newVerifique != verifique)
    {
      NotificationChain msgs = null;
      if (verifique != null)
        msgs = ((InternalEObject)verifique).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AtadPackage.COMANDOS_VALIDADORES__VERIFIQUE, null, msgs);
      if (newVerifique != null)
        msgs = ((InternalEObject)newVerifique).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AtadPackage.COMANDOS_VALIDADORES__VERIFIQUE, null, msgs);
      msgs = basicSetVerifique(newVerifique, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AtadPackage.COMANDOS_VALIDADORES__VERIFIQUE, newVerifique, newVerifique));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AtadPackage.COMANDOS_VALIDADORES__VERIFIQUE:
        return basicSetVerifique(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AtadPackage.COMANDOS_VALIDADORES__VERIFIQUE:
        return getVerifique();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AtadPackage.COMANDOS_VALIDADORES__VERIFIQUE:
        setVerifique((VerifiquePresente)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AtadPackage.COMANDOS_VALIDADORES__VERIFIQUE:
        setVerifique((VerifiquePresente)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AtadPackage.COMANDOS_VALIDADORES__VERIFIQUE:
        return verifique != null;
    }
    return super.eIsSet(featureID);
  }

} //ComandosValidadoresImpl
