/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad.impl;

import com.ufrn.atad.atad.AtadPackage;
import com.ufrn.atad.atad.ComandosValidadores;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Comandos Validadores</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ComandosValidadoresImpl extends MinimalEObjectImpl.Container implements ComandosValidadores
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComandosValidadoresImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AtadPackage.Literals.COMANDOS_VALIDADORES;
  }

} //ComandosValidadoresImpl
