/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad.impl;

import com.ufrn.atad.atad.AtadPackage;
import com.ufrn.atad.atad.DeclaraComando;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Declara Comando</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.ufrn.atad.atad.impl.DeclaraComandoImpl#getComandos <em>Comandos</em>}</li>
 *   <li>{@link com.ufrn.atad.atad.impl.DeclaraComandoImpl#getAcoes <em>Acoes</em>}</li>
 *   <li>{@link com.ufrn.atad.atad.impl.DeclaraComandoImpl#getVerificacao <em>Verificacao</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DeclaraComandoImpl extends MinimalEObjectImpl.Container implements DeclaraComando
{
  /**
   * The cached value of the '{@link #getComandos() <em>Comandos</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComandos()
   * @generated
   * @ordered
   */
  protected EList<String> comandos;

  /**
   * The cached value of the '{@link #getAcoes() <em>Acoes</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAcoes()
   * @generated
   * @ordered
   */
  protected EList<String> acoes;

  /**
   * The cached value of the '{@link #getVerificacao() <em>Verificacao</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVerificacao()
   * @generated
   * @ordered
   */
  protected EList<String> verificacao;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeclaraComandoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AtadPackage.Literals.DECLARA_COMANDO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getComandos()
  {
    if (comandos == null)
    {
      comandos = new EDataTypeEList<String>(String.class, this, AtadPackage.DECLARA_COMANDO__COMANDOS);
    }
    return comandos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getAcoes()
  {
    if (acoes == null)
    {
      acoes = new EDataTypeEList<String>(String.class, this, AtadPackage.DECLARA_COMANDO__ACOES);
    }
    return acoes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getVerificacao()
  {
    if (verificacao == null)
    {
      verificacao = new EDataTypeEList<String>(String.class, this, AtadPackage.DECLARA_COMANDO__VERIFICACAO);
    }
    return verificacao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AtadPackage.DECLARA_COMANDO__COMANDOS:
        return getComandos();
      case AtadPackage.DECLARA_COMANDO__ACOES:
        return getAcoes();
      case AtadPackage.DECLARA_COMANDO__VERIFICACAO:
        return getVerificacao();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AtadPackage.DECLARA_COMANDO__COMANDOS:
        getComandos().clear();
        getComandos().addAll((Collection<? extends String>)newValue);
        return;
      case AtadPackage.DECLARA_COMANDO__ACOES:
        getAcoes().clear();
        getAcoes().addAll((Collection<? extends String>)newValue);
        return;
      case AtadPackage.DECLARA_COMANDO__VERIFICACAO:
        getVerificacao().clear();
        getVerificacao().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AtadPackage.DECLARA_COMANDO__COMANDOS:
        getComandos().clear();
        return;
      case AtadPackage.DECLARA_COMANDO__ACOES:
        getAcoes().clear();
        return;
      case AtadPackage.DECLARA_COMANDO__VERIFICACAO:
        getVerificacao().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AtadPackage.DECLARA_COMANDO__COMANDOS:
        return comandos != null && !comandos.isEmpty();
      case AtadPackage.DECLARA_COMANDO__ACOES:
        return acoes != null && !acoes.isEmpty();
      case AtadPackage.DECLARA_COMANDO__VERIFICACAO:
        return verificacao != null && !verificacao.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (comandos: ");
    result.append(comandos);
    result.append(", acoes: ");
    result.append(acoes);
    result.append(", verificacao: ");
    result.append(verificacao);
    result.append(')');
    return result.toString();
  }

} //DeclaraComandoImpl
