/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad.impl;

import com.ufrn.atad.atad.AtadPackage;
import com.ufrn.atad.atad.Escrever;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Escrever</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.ufrn.atad.atad.impl.EscreverImpl#getTipoLocalizador <em>Tipo Localizador</em>}</li>
 *   <li>{@link com.ufrn.atad.atad.impl.EscreverImpl#getConteudo <em>Conteudo</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EscreverImpl extends ComandosAcaoImpl implements Escrever
{
  /**
   * The default value of the '{@link #getTipoLocalizador() <em>Tipo Localizador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoLocalizador()
   * @generated
   * @ordered
   */
  protected static final String TIPO_LOCALIZADOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTipoLocalizador() <em>Tipo Localizador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoLocalizador()
   * @generated
   * @ordered
   */
  protected String tipoLocalizador = TIPO_LOCALIZADOR_EDEFAULT;

  /**
   * The default value of the '{@link #getConteudo() <em>Conteudo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConteudo()
   * @generated
   * @ordered
   */
  protected static final String CONTEUDO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getConteudo() <em>Conteudo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConteudo()
   * @generated
   * @ordered
   */
  protected String conteudo = CONTEUDO_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EscreverImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AtadPackage.Literals.ESCREVER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTipoLocalizador()
  {
    return tipoLocalizador;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoLocalizador(String newTipoLocalizador)
  {
    String oldTipoLocalizador = tipoLocalizador;
    tipoLocalizador = newTipoLocalizador;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AtadPackage.ESCREVER__TIPO_LOCALIZADOR, oldTipoLocalizador, tipoLocalizador));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getConteudo()
  {
    return conteudo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setConteudo(String newConteudo)
  {
    String oldConteudo = conteudo;
    conteudo = newConteudo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AtadPackage.ESCREVER__CONTEUDO, oldConteudo, conteudo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AtadPackage.ESCREVER__TIPO_LOCALIZADOR:
        return getTipoLocalizador();
      case AtadPackage.ESCREVER__CONTEUDO:
        return getConteudo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AtadPackage.ESCREVER__TIPO_LOCALIZADOR:
        setTipoLocalizador((String)newValue);
        return;
      case AtadPackage.ESCREVER__CONTEUDO:
        setConteudo((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AtadPackage.ESCREVER__TIPO_LOCALIZADOR:
        setTipoLocalizador(TIPO_LOCALIZADOR_EDEFAULT);
        return;
      case AtadPackage.ESCREVER__CONTEUDO:
        setConteudo(CONTEUDO_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AtadPackage.ESCREVER__TIPO_LOCALIZADOR:
        return TIPO_LOCALIZADOR_EDEFAULT == null ? tipoLocalizador != null : !TIPO_LOCALIZADOR_EDEFAULT.equals(tipoLocalizador);
      case AtadPackage.ESCREVER__CONTEUDO:
        return CONTEUDO_EDEFAULT == null ? conteudo != null : !CONTEUDO_EDEFAULT.equals(conteudo);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (tipoLocalizador: ");
    result.append(tipoLocalizador);
    result.append(", conteudo: ");
    result.append(conteudo);
    result.append(')');
    return result.toString();
  }

} //EscreverImpl
