/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad.impl;

import com.ufrn.atad.atad.AtadPackage;
import com.ufrn.atad.atad.Espera;
import com.ufrn.atad.atad.TipoLocalizadores;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Espera</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.ufrn.atad.atad.impl.EsperaImpl#getTipoLocalizador <em>Tipo Localizador</em>}</li>
 *   <li>{@link com.ufrn.atad.atad.impl.EsperaImpl#getName <em>Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EsperaImpl extends ComandoImpl implements Espera
{
  /**
   * The default value of the '{@link #getTipoLocalizador() <em>Tipo Localizador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoLocalizador()
   * @generated
   * @ordered
   */
  protected static final TipoLocalizadores TIPO_LOCALIZADOR_EDEFAULT = TipoLocalizadores.XPATH;

  /**
   * The cached value of the '{@link #getTipoLocalizador() <em>Tipo Localizador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipoLocalizador()
   * @generated
   * @ordered
   */
  protected TipoLocalizadores tipoLocalizador = TIPO_LOCALIZADOR_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EsperaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AtadPackage.Literals.ESPERA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TipoLocalizadores getTipoLocalizador()
  {
    return tipoLocalizador;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipoLocalizador(TipoLocalizadores newTipoLocalizador)
  {
    TipoLocalizadores oldTipoLocalizador = tipoLocalizador;
    tipoLocalizador = newTipoLocalizador == null ? TIPO_LOCALIZADOR_EDEFAULT : newTipoLocalizador;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AtadPackage.ESPERA__TIPO_LOCALIZADOR, oldTipoLocalizador, tipoLocalizador));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AtadPackage.ESPERA__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AtadPackage.ESPERA__TIPO_LOCALIZADOR:
        return getTipoLocalizador();
      case AtadPackage.ESPERA__NAME:
        return getName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AtadPackage.ESPERA__TIPO_LOCALIZADOR:
        setTipoLocalizador((TipoLocalizadores)newValue);
        return;
      case AtadPackage.ESPERA__NAME:
        setName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AtadPackage.ESPERA__TIPO_LOCALIZADOR:
        setTipoLocalizador(TIPO_LOCALIZADOR_EDEFAULT);
        return;
      case AtadPackage.ESPERA__NAME:
        setName(NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AtadPackage.ESPERA__TIPO_LOCALIZADOR:
        return tipoLocalizador != TIPO_LOCALIZADOR_EDEFAULT;
      case AtadPackage.ESPERA__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (tipoLocalizador: ");
    result.append(tipoLocalizador);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //EsperaImpl
