/**
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.atad.impl;

import com.ufrn.atad.atad.AtadPackage;
import com.ufrn.atad.atad.VerifiqueNaoPresente;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Verifique Nao Presente</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VerifiqueNaoPresenteImpl extends ComandosValidadoresImpl implements VerifiqueNaoPresente
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VerifiqueNaoPresenteImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AtadPackage.Literals.VERIFIQUE_NAO_PRESENTE;
  }

} //VerifiqueNaoPresenteImpl
