/*
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.parser.antlr;

import com.google.inject.Inject;
import com.ufrn.atad.parser.antlr.internal.InternalAtadParser;
import com.ufrn.atad.services.AtadGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AtadParser extends AbstractAntlrParser {

	@Inject
	private AtadGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAtadParser createParser(XtextTokenStream stream) {
		return new InternalAtadParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DeclaraComando";
	}

	public AtadGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AtadGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
