/*
 * generated by Xtext 2.25.0
 */
package com.ufrn.atad.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AtadAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/ufrn/atad/parser/antlr/internal/InternalAtad.tokens");
	}
}
